### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by Caspering** [Caspering/inventory_management#14]
In postman processed food's get request works when searched by ID but doesnt when searched by food type.
example: /api/v1/processedFoods/VEGAN returns an error log
/api/v1/processedFoods/by-name/VEGAN returns an error log

these should return all processed foodtype VEGAN.
![buggy](https://user-images.githubusercontent.com/35642296/81242371-cc768180-8fc1-11ea-8810-a84e76744416.png)

**Comment by ghost** [comment]
As I mentioned in my pull request, I modified the processedFoods endpoint to accept an optional type query parameter, so the request would be on an endpoint like this:

http://localhost:8080/api/v1/processedFoods?type=VEGAN

This design made sense to me, since that is the list processedFoods endpoint. Adding the type parameter filters by type.
